num1 =rbind(rep("a",3), rep("b",3), rep("c",3))
print("num1")
print(num1)
num2 = rbind(rep("p",3), rep("q",3), rep("r",3))
print("num2")
print(num2)
num3 = rbind(rep("x",3), rep("y",3), rep("z",3))
print("num3")
print(num3)
a = matrix(t(cbind(num1,num2,num3)),ncol=3, byrow=T)
print("combine three arrays, taking one row from each one by one:")
print(a)
